# Generated by Django 2.2.6 on 2019-10-06 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Bills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Bills.Bill')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Products.Product')),
            ],
        ),
    ]
